apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub-master
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeredLittle1/argo-master-app
    targetRevision: HEAD
    path: jupyterhub/
  destination: 
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true