apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-master
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeredLittle1/argo-master-app
    targetRevision: HEAD
    path: nginx/
  destination: 
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true