apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-master
  namespace: compute-plane
spec:
  project: default
  source:
    repoURL: https://github.com/JeredLittle1/argo-master-app
    targetRevision: HEAD
    path: argo-workflows/
    helm:
      values: |
        gcp:
          enabled: true
          iap:
            enabled: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: compute-plane
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true