apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-master
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeredLittle1/argo-master-app
    targetRevision: HEAD
    path: kube-prometheus-stack/
    helm:
      values: |
        grafana:
          local: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true