apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-secrets
  namespace: compute-plane
spec:
  project: default
  source:
    repoURL: https://github.com/JeredLittle1/team-engineering
    targetRevision: HEAD
    path: sealed-secrets/
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: compute-plane
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true