apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-kubernetes-default
  namespace: compute-plane
spec:
  encryptedData:
    AIRFLOW_CONN_KUBERNETES_DEFAULT: AgCMFg/qense/W6mwoPy6m4AHuGQEagVFb1qtYZYYnWFa9Un52xIt4Pv7cbpImw/iKcVOmyq5VYwJtpMBRaOY6QWy1TGpzuOp4GywEfGPVjepTJYz6ZOOrEMtDMA7uEzQkzMFXAXPfuoXuhpgNfQajvb/cFkJ1QLQLJjpKcVKdX4SzygXVJk6BN9mkn0SDAq7BCXroU28WWAyQFzI5mcnOGF3juiIQZhjEw3FEnOufwi7MaNG1nIil6oTPUjIp/GnywoKHHZbBqamiXTeIrT+6wcxPpvxqGvkusqfsuXheifjn589Eh1H6fMeJsYct/DNCwaGTWR3I34Ai5BOFPlWstqqVWYndcn2+oTdioOfWECBux0bqj0LY+CxXC6cfNDxc5bzM5xngngvKzq3vBL/vIHVemsQxNZxFkFHlCzfDTwV5pdlY1JlweltNhqghYUFOJsAOLzSBOBQ3yMHNOHOEO9dimr0ODeOdN6ePa5+wNwPSuyauZmRqpp3rMXeMa5gLggMfIsE4I5epYkcWS7hRcfdgMTPpRSe37UTK86yfcw3uDVsq3nS3w1sLTfU3Qng242njJ7LlpDOKIMmgG+LXUDNde+zWJlKhriRMbYaVZO860dyQm/w0ACWak01j480c8bgxCSsBKu2INyh0XWZR8NjCF3fdkV0l+VZbG8dNJRgL15gi9hTPuD3KkMJok0XPhj+0Nf8IZBhZTVvy5H3b5ShXSARSUcHFkgZNqKaqBF+YCQ8S7IR0d0+P9n1vtzjWKrSQrbel8jcFxMXWcFiHgMWJ4r58fIwhsBiEZQzQGZ06A2lVKFBoO8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-kubernetes-default
      namespace: compute-plane
    type: Opaque